name: featuregen
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/MansurSarkhanov/featuregen

environment:
  sdk: ^3.10.1
  
executables:
  featuregen:
# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
