name: feature_structure
description: A Dart CLI tool to generate clean feature-first folder structures for Flutter projects.
version: 1.0.3
repository: https://github.com/MansurSarkhanov/featuregen

environment:
  sdk: ^3.10.1
  
executables:
  feature_structure:
# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
